#configuration

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/cropmaster
spring.datasource.username=root
spring.datasource.password=7720

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=VGhpc0lzQUNyb3BNYXN0ZXJKV1RTZWNyZXRLZXlGb3JEZXZlbG9wbWVudDEyMzQ1Njc4OTA=
jwt.expiration-ms=86400000
